# Generated by Django 5.1.4 on 2025-01-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_delete_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_sent',
            field=models.BooleanField(default=False),
        ),
    ]
